FROM node:20-alpine

WORKDIR /app

ARG DATABASE_URL

COPY ./package.json /package.json

COPY ./package-lock.json /package-lock.json

COPY ./turbo.json ./turbo.json

RUN npm install

COPY . .

ENV DATABASE_URL=${DATABASE_URL}  

RUN npm run generate:db

RUN npm run build

EXPOSE 8080

CMD ["npm","start:http-server"]
